INSERT INTO roles(name) values ('editor');
INSERT INTO roles(name) values ('reader');
INSERT INTO rules(name, role_id) values ('create', 1);
INSERT INTO rules(name, role_id) values ('delete', 1);
INSERT INTO rules(name, role_id) values ('read', 1);
INSERT INTO rules(name, role_id) values ('read', 2);
INSERT INTO states(name) values ('new');
INSERT INTO states(name) values ('working');
INSERT INTO categories(name) values ('low');
INSERT INTO categories(name) values ('medium');
INSERT INTO categories(name) values ('urgent');
INSERT INTO users (name, role_id) values ('Super User', 1);
INSERT INTO users (name, role_id) values ('Just User', 2);
INSERT INTO items (name, state_id, category_id, user_id) values ('fix all bugs', 1, 3, 1);
INSERT INTO items (name, state_id, category_id, user_id) values ('help me please', 2, 2, 2);
INSERT INTO comments (comment, item_id) values ('first comment about bugs', 1);
INSERT INTO comments (comment, item_id) values ('second comment about bugs', 1);
INSERT INTO comments (comment, item_id) values ('some comment abour help', 2);
INSERT INTO attachs (file_name, item_id) values ('system.png', 1);
